language: python
python:
- '2.7'
sudo: required
services:
- docker
install: true
env:
  global:
  #QUAY_LOGIN
  #QUAY_PASSWORD
  - secure: d7jSH+2is04BynmFIUayTwQewGCZCcXxBjZD5386B6nwOEN0KE1POxVHkgt2G2vUb05+tcCxVw0qPAGUatdB2PR6tbCTMctKR9dlx9YuzG7+ldFm/plLdAGuU9ig/O5pPI2RqfF5hAYw8j0w9CuEsj3q/UXk37NGUbObsG6RdvEHwUJNoLa0yt00Lc4s8gHpepP6b+LrUrPRBo1UOljw/9aZksEp0TW9yXC6KVEq+A8iHRi9nGPcAPtGk1pq8cxXsyV3MfLvUoFG0lfJmn5/W5DokJFkSi5o9rbOvsnAhReyrQNvcsYHvLTM7D+B8Ns01lEwk/1Rmgi3SVSsfz77o7sOWY4enEOxD1o/yQ+7poHN98wFpCUBBS6hOuDxvef42KpS/HB5NiT2ts+cbJ3cA5fxG0feZNRb+NHctstPy5V3LBLxwQKAmEShQQrbpKUZhGSJP0vgEpccaQTK+kflBdbS1OtqC4IMg+CIzf5GFV/pFILf+BPr2afGj3bzjmBVMZXW9msYuw4ozHroJTP965cnZzBCsIP+ecrXiAF8zObaCltf8/TUY8V1iDxlAtnBJj64XPsrBV7VAzeLNLFAfuAN1y1PDoL7GPp1wDbyd9Q727oxhCI2was76D8SOyeVY2BDZJMzpSaoTKSdqX9rbTrfv5Sn5K/nxBX34BbYP3w=
  - secure: l++S6wYIfjWxNZTTgwOueS7kvzkjeg5K15jJ4uRSeFCUNHPPpbquXte+mFsjIAWQZc0iejRlYvJkyxVFRqkh+oAospPNNC5woB8TILu2rsi3Dkr9aBzjD3nUo401VcDa8MXJEMBmRRJ7TmwynC+b/Ir5/TG7OZJsEJTkO8Mq50oLKfp1dC8cujh45XpmkCQ+uNzW1ctEiWWonUAP8Y+aDMtB36NevsV2OBYr3VwHQWWsWDXML/0a+bge7Pold2rsg4s5N8ve4M8ybTQOPsjQWOCBIZQa84Rk9VqVCAwgDQXIR2xMfC9SoLx+8mLp+ocyjzDXe1/YvEu99xFRfFkX0Xhra9/wNk9MFtjX3GmnB7OxcB2nZyFJz6p4YOfHIG5fn1/cjA5X4qLtBfvspNY0vUIcQc5Cj+0OfxWujgdF4ckpbeQFYuY0n/dsq2F3aku/pU+FTnY6Qe9fV82HuXJcOQ/cZ+GBzWXFuSXUlOzE/aoLrJxJybUXfynk+urUzlj/lpKEbOp1P/kQeI8WA9qRebQgioxPHwt5s75kghO2IaStvqrbi4LSEfm8Y7Z95v1qnWHzzfc5ynPQlODqspLSrg82KDCq8VDC6H4ijZmvC6evUmnGB2TkwTUmZXyGpnD1zQoqqjQkRSLmBL9cdY4VE0B4/r0/lsjhJu6PldEH4/M=
script:
- docker login quay.io -u="$QUAY_LOGIN" -p="$QUAY_PASSWORD"
- docker pull quay.io/ottojolanki/pipeline-images
- ./test.sh
